### ISSUE TITLE
latest_net_G.pth

### ISSUE THREAD

**Issue by xiaoachen98** [EndlessSora/TSIT#13]
Thank you very much for your excellent work.I want to use your Sunny2Diffweather model to make Finetune, which requires the parameters of G and D. However, you only provided the parameter of G, so I would like to request it. Just need SUNNY2DIFFWEATHER LATEST_NET_D.PTH, thank you very much!!

**Comment by EndlessSora** [comment]
Thanks for your interest. Could you please send an email to me or provide your email address?

**Comment by xiaoachen98** [comment]
Thanks!
chlin@mail.ustc.edu.cn
