### ISSUE TITLE
Why do you put FADE before Conv?

### ISSUE THREAD

**Issue by s1ddok** [EndlessSora/TSIT#2]
I see that you inherited approach from SPADE where SPADE is located before Conv in SPADEResnetBlock, can you explain the motivation?

**Comment by EndlessSora** [comment]
[Norm-Activation-{Conv]-[Norm-Activation}-Conv] should be similar as [Conv-Activation-{Norm]-[Conv-Activation}-Norm]. We follow SPADE ResBlk to design its generalization FADE ResBlk.
