### ISSUE TITLE
How to get FID?

### ISSUE THREAD

**Issue by cyq373** [EndlessSora/TSIT#7]
For the season transfer task, how to get the FID score?

**Comment by VipulRamtekkar** [comment]
Hi,

To calculate FID scores you can try using pytorch-fid. 

~~pip install pytorch-fid~~

Usage
~~​python -m pytorch_fid path/to/dataset1 path/to/dataset2~~

**Comment by cyq373** [comment]
@VipulRamtekkar Thanks!
